import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="justify-center items-center w-100 h-20 flex gap-x-60 font-bold text-lg">
          <Link href="/">HOME</Link>
          <Link href="/about">ABOUT</Link>
          <Link href="/report">REPORT</Link>
          <Link href="/todo-csr">TODOS-CSR</Link>
          <Link href="/todo-ssr">TODOS-SSR</Link>
        </nav>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
