import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <nav className="justify-center items-center w-full bg-black h-20 flex gap-x-40 font-bold text-lg">
      <Link href="/" className="text-white hover-gradient-text" data-text="HOME">HOME</Link>
      <Link href="/about" className="text-white hover-gradient-text" data-text="ABOUT">ABOUT</Link>
      <Link href="/report" className="text-white hover-gradient-text" data-text="REPORT">REPORT</Link>
      <Link href="/todo-csr" className="text-white hover-gradient-text" data-text="TODOS-CSR">TODOS-CSR</Link>
      <Link href="/todo-ssr" className="text-white hover-gradient-text" data-text="TODOS-SSR">TODOS-SSR</Link>
      </nav>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
